### ISSUE TITLE
Test new glossary.ttl structure

### ISSUE THREAD

**Issue by AndyClifton** [IEA-Wind-Task-32/wind-lidar-glossary#1]
@niva83 I've implemented some basic definitions with hierarchical structure in the [`glossary.ttl`](https://github.com/IEA-Wind-Task-32/wind-lidar-glossary/blob/main/glossary.ttl) file.

There should now be a hierarchical relationship that goes something like this:
- devices
  - wind scanner
- measurement principles
  - scanning geometry
    - velocity azimuth display (VAD)

If this is working, let's break up `glossary.ttl` into separate files for `devices`, `measurement principles`, and other top-level concepts. If you can give me a template for those I can implement it fairly easily.

**Comment by niva83** [comment]
That makes sense, maybe you want to think of categorizing devices to CW and pulsed lidars?

**Comment by AndyClifton** [comment]
I would push things like CW or pulsed to measurement principles. Could you confirm that the file works, and then tell me how I should break it up, please?

**Comment by AndyClifton** [comment]
Closing this as it has now been implemented. The solution is to create multiple .txt files that are then merged into a single .ttl file by a GitHub action.
