### ISSUE TITLE
Change name from wind-lidar-glossary to wind-lidar-ontology

### ISSUE THREAD

**Issue by niva83** [IEA-Wind-Task-32/wind-lidar-glossary#4]
@AndyClifton I think we can agree that what has been built here is not a glossary but ontology of wind lidars.
Therefore, I think we should change the name :)

**Comment by AndyClifton** [comment]
Good point. The challenge with this is that may cause a lot of folks to say "huh?", and think that it's not relevant for them. I think we can avoid that by careful explanation.

Suggestion:
0. [ ] I rename the repo (risky, but better now than later)
1. I rename glossary.ttl to ontology.ttl
2. I update the readme to make it clear that it can still be considered a glossary (if approached from that direction)
3. I fix all of the CI on GitHub.

**Comment by niva83** [comment]
True... that risk actually tells us to stick to the glossary for time being until we get it further developed and show the practical aspects of using it.

**Comment by AndyClifton** [comment]
An alternative would be to combine `glossary.ttl` with `parameters.txt` to generate `ontology.ttl`. 

I like that as a solution.

**Comment by niva83** [comment]
I think we have a winning solution!

**Comment by AndyClifton** [comment]
Implemented in https://github.com/IEA-Wind-Task-32/wind-lidar-glossary/commit/8bd7c1ae5fe2959fe2158cf64bd594eea60a5b4d.
